apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-flask-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: flask.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: api-flask
            port:
              number: 80